---

   - name: fetch a linux distro name/version
     debug:
       msg:
         - "hostname: {{ ansible_hostname }}"
         - "distro_name: {{ ansible_distribution }}"
         - "distro_version: {{ ansible_distribution_version }}"
